CREATE TABLE IF NOT EXISTS `#__bg_persons` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(255) NOT NULL DEFAULT '',
  `prefix` varchar(100) NOT NULL DEFAULT '',
  `lastname` varchar(255) NOT NULL DEFAULT '',
  `alternative_name` varchar(255) NOT NULL DEFAULT '',
  `nickname` varchar(255) NOT NULL DEFAULT '',
  `gender` varchar(10) NOT NULL DEFAULT '',
  `birth_date` date DEFAULT NULL,
  `birth_place` varchar(255) NOT NULL DEFAULT '',
  `death_date` date DEFAULT NULL,
  `death_place` varchar(255) NOT NULL DEFAULT '',
  `occupation` varchar(255) NOT NULL DEFAULT '',
  `street` varchar(255) NOT NULL DEFAULT '',
  `house_number` varchar(50) NOT NULL DEFAULT '',
  `postal_code` varchar(50) NOT NULL DEFAULT '',
  `city` varchar(255) NOT NULL DEFAULT '',
  `country` varchar(255) NOT NULL DEFAULT '',
  `phone` varchar(100) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `website` varchar(500) NOT NULL DEFAULT '',
  `photo` varchar(500) NOT NULL DEFAULT '',
  `gallery_images` mediumtext,

  `birth_card_front` text NULL,
  `birth_card_inside_left` text NULL,
  `birth_card_inside_right` text NULL,
  `birth_card_back` text NULL,
  `memorial_card_front` text NULL,
  `memorial_card_inside_left` text NULL,
  `memorial_card_inside_right` text NULL,
  `memorial_card_back` text NULL,
  `biography` mediumtext,
  `notes` mediumtext,
  `show_nickname` tinyint(1) NOT NULL DEFAULT '1',
  `show_firstname` tinyint(1) NOT NULL DEFAULT '1',
  `show_prefix` tinyint(1) NOT NULL DEFAULT '1',
  `show_lastname` tinyint(1) NOT NULL DEFAULT '1',
  `show_alternative_name` tinyint(1) NOT NULL DEFAULT '1',
  `show_birth_date` tinyint(1) NOT NULL DEFAULT '1',
  `show_birth_place` tinyint(1) NOT NULL DEFAULT '1',
  `show_death_date` tinyint(1) NOT NULL DEFAULT '1',
  `show_death_place` tinyint(1) NOT NULL DEFAULT '1',
  `show_occupation` tinyint(1) NOT NULL DEFAULT '1',
  `show_street` tinyint(1) NOT NULL DEFAULT '1',
  `show_house_number` tinyint(1) NOT NULL DEFAULT '1',
  `show_postal_code` tinyint(1) NOT NULL DEFAULT '1',
  `show_city` tinyint(1) NOT NULL DEFAULT '1',
  `show_country` tinyint(1) NOT NULL DEFAULT '1',
  `show_phone` tinyint(1) NOT NULL DEFAULT '1',
  `show_email` tinyint(1) NOT NULL DEFAULT '1',
  `show_website` tinyint(1) NOT NULL DEFAULT '1',
  `show_biography` tinyint(1) NOT NULL DEFAULT '1',
  `show_notes` tinyint(1) NOT NULL DEFAULT '1',
  `living` tinyint(1) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_bg_persons_lastname` (`lastname`),
  KEY `idx_bg_persons_birth_date` (`birth_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__bg_families` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `husband_id` int unsigned DEFAULT NULL,
  `wife_id` int unsigned DEFAULT NULL,
  `marriage_date` date DEFAULT NULL,
  `marriage_place` varchar(255) NOT NULL DEFAULT '',
  `divorce_date` date DEFAULT NULL,
  `wedding_card_front` text NULL,
  `wedding_card_inside_left` text NULL,
  `wedding_card_inside_right` text NULL,
  `wedding_card_back` text NULL,
  `marriage_certificate_front` text NULL,
  `marriage_certificate_page_2` text NULL,
  `marriage_certificate_page_3` text NULL,
  `marriage_certificate_back` text NULL,
  `notes` mediumtext,
  PRIMARY KEY (`id`),
  KEY `idx_bg_families_husband` (`husband_id`),
  KEY `idx_bg_families_wife` (`wife_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__bg_children` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `family_id` int unsigned NOT NULL,
  `person_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bg_children` (`family_id`,`person_id`),
  KEY `idx_bg_children_person` (`person_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
